<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net481</TargetFramework>
		<OutputType>Library</OutputType>
		<RootNamespace>Iridium</RootNamespace>
		<AssemblyName>Iridium</AssemblyName>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<OutputPath>..\bin\v3\</OutputPath>
		<AllowUnsafeBlocks>false</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>portable</DebugType>
		<Optimize>false</Optimize>
		<DefineConstants>DEBUG;TRACE;ADOFAI_2_10_0</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<DebugType>portable</DebugType>
		<Optimize>true</Optimize>
		<DefineConstants>TRACE;ADOFAI_2_10_0</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\runtime\abstractions\Iridium.Runtime.Abstractions.csproj">
			<Private>true</Private>
		</ProjectReference>
		<ProjectReference Include="..\runtime\mono\Iridium.Runtime.Mono.csproj" />
		<ProjectReference Include="..\runtime\il2cpp\Iridium.Runtime.Il2Cpp.csproj" ReferenceOutputAssembly="false" />
		<Reference Include="0Harmony">
			<HintPath>..\lib\ModManager\0Harmony.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<ProjectReference Include="..\architectury\Iris.Iml\Iris.Iml.csproj" />
		<Reference Include="Assembly-CSharp">
			<HintPath>..\lib\v3.3.0\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="Assembly-CSharp-firstpass">
			<HintPath>..\lib\v3.3.0\Assembly-CSharp-firstpass.dll</HintPath>
		</Reference>
		<Reference Include="SkyHook.Unity">
			<HintPath>..\lib\v3.3.0\SkyHook.Unity.dll</HintPath>
		</Reference>
		<Reference Include="DOTween">
			<HintPath>..\lib\v2.9.8\DOTween.dll</HintPath>
		</Reference>
		<Reference Include="DOTweenPro">
			<HintPath>..\lib\v2.9.8\DOTweenPro.dll</HintPath>
		</Reference>
		<Reference Include="RDTools">
			<HintPath>..\lib\v2.9.8\RDTools.dll</HintPath>
		</Reference>
		<Reference Include="Newtonsoft.Json">
			<HintPath>..\lib\v2.9.8\Newtonsoft.Json.dll</HintPath>
		</Reference>
		<Reference Include="System.Drawing" />
		<Reference Include="UnityEngine">
			<HintPath>..\lib\v2.9.8\UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AccessibilityModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.AccessibilityModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AIModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.AIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AndroidJNIModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.AndroidJNIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AnimationModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.AnimationModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ARModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.ARModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AssetBundleModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.AssetBundleModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AudioModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.AudioModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ClothModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.ClothModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ClusterInputModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.ClusterInputModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ClusterRendererModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.ClusterRendererModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ContentLoadModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.ContentLoadModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CrashReportingModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.CrashReportingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.DirectorModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.DirectorModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.DSPGraphModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.DSPGraphModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GameCenterModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.GameCenterModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GIModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.GIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GridModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.GridModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.HotReloadModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.HotReloadModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ImageConversionModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.ImageConversionModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.IMGUIModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.IMGUIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputLegacyModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.InputLegacyModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.InputModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.JSONSerializeModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.JSONSerializeModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.LocalizationModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.LocalizationModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.NVIDIAModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.NVIDIAModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ParticleSystemModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.ParticleSystemModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PerformanceReportingModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.PerformanceReportingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.Physics2DModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.Physics2DModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PhysicsModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.PhysicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ProfilerModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.ProfilerModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PropertiesModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.PropertiesModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.Purchasing">
			<HintPath>..\lib\v2.9.8\UnityEngine.Purchasing.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.Purchasing.AppleCore">
			<HintPath>..\lib\v2.9.8\UnityEngine.Purchasing.AppleCore.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.Purchasing.AppleMacosStub">
			<HintPath>..\lib\v2.9.8\UnityEngine.Purchasing.AppleMacosStub.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.Purchasing.AppleStub">
			<HintPath>..\lib\v2.9.8\UnityEngine.Purchasing.AppleStub.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.Purchasing.Codeless">
			<HintPath>..\lib\v2.9.8\UnityEngine.Purchasing.Codeless.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.Purchasing.SecurityCore">
			<HintPath>..\lib\v2.9.8\UnityEngine.Purchasing.SecurityCore.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.Purchasing.SecurityStub">
			<HintPath>..\lib\v2.9.8\UnityEngine.Purchasing.SecurityStub.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.Purchasing.Stores">
			<HintPath>..\lib\v2.9.8\UnityEngine.Purchasing.Stores.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.Purchasing.WinRTCore">
			<HintPath>..\lib\v2.9.8\UnityEngine.Purchasing.WinRTCore.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.Purchasing.WinRTStub">
			<HintPath>..\lib\v2.9.8\UnityEngine.Purchasing.WinRTStub.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ScreenCaptureModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.ScreenCaptureModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SharedInternalsModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.SharedInternalsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SpriteMaskModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.SpriteMaskModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SpriteShapeModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.SpriteShapeModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.StreamingModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.StreamingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SubstanceModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.SubstanceModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SubsystemsModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.SubsystemsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TerrainModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.TerrainModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TerrainPhysicsModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.TerrainPhysicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextCoreFontEngineModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextCoreTextEngineModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.TextCoreTextEngineModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextRenderingModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.TextRenderingModule.dll</HintPath>
		</Reference>
		<Reference Include="Unity.TextMeshPro">
			<HintPath>..\lib\v3.3.0\Unity.TextMeshPro.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TilemapModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.TilemapModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TLSModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.TLSModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UI">
			<HintPath>..\lib\v2.9.8\UnityEngine.UI.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UIElementsModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.UIElementsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UIModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.UIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UmbraModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.UmbraModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityAnalyticsCommonModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityAnalyticsModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.UnityAnalyticsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityConnectModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.UnityConnectModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityCurlModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.UnityCurlModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityTestProtocolModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.UnityTestProtocolModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestAudioModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.UnityWebRequestModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestTextureModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestWWWModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VehiclesModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.VehiclesModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VFXModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.VFXModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VideoModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.VideoModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VirtualTexturingModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.VirtualTexturingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VRModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.VRModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.WindModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.WindModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.XRModule">
			<HintPath>..\lib\v2.9.8\UnityEngine.XRModule.dll</HintPath>
		</Reference>

	</ItemGroup>
	<ItemGroup>
		<None Update="Info.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<Target Name="PrintVersion" BeforeTargets="BeforeBuild">
		<Message Text="=== Building Iridium for ADOFAI v3.3.0 ===" Importance="high" />
	</Target>
	<Target Name="CopyToOut" AfterTargets="Build">
		<PropertyGroup>
			<OutDir>$(ProjectDir)..\out\v3\</OutDir>
		</PropertyGroup>
		<MakeDir Directories="$(OutDir)" />
		<MakeDir Directories="$(OutDir)Resources" />
		<ItemGroup>
			<FilesToCopy Include="$(OutputPath)$(AssemblyName).dll" />
			<FilesToCopy Include="$(OutputPath)Iridium.Runtime.Abstractions.dll" Condition="Exists('$(OutputPath)Iridium.Runtime.Abstractions.dll')" />
			<FilesToCopy Include="$(ProjectDir)..\bin\runtime\mono\Iridium.Runtime.Mono.dll" Condition="Exists('$(ProjectDir)..\bin\runtime\mono\Iridium.Runtime.Mono.dll')" />
			<FilesToCopy Include="$(ProjectDir)..\bin\runtime\il2cpp\Iridium.Runtime.Il2Cpp.dll" Condition="Exists('$(ProjectDir)..\bin\runtime\il2cpp\Iridium.Runtime.Il2Cpp.dll')" />
			<FilesToCopy Include="$(ProjectDir)..\bin\loaders\umm\$(TargetFramework)\Iridium.Loader.UMM.dll" Condition="Exists('$(ProjectDir)..\bin\loaders\umm\$(TargetFramework)\Iridium.Loader.UMM.dll')" />
			<FilesToCopy Include="$(ProjectDir)..\bin\loaders\melon\$(TargetFramework)\Iridium.Loader.Melon.dll" Condition="Exists('$(ProjectDir)..\bin\loaders\melon\$(TargetFramework)\Iridium.Loader.Melon.dll')" />
			<FilesToCopy Include="$(ProjectDir)..\bin\loaders\bepinex\$(TargetFramework)\Iridium.Loader.BepInEx.dll" Condition="Exists('$(ProjectDir)..\bin\loaders\bepinex\$(TargetFramework)\Iridium.Loader.BepInEx.dll')" />
			<FilesToCopy Include="$(ProjectDir)..\out\Iris.Iml\Iris.Iml.dll" Condition="Exists('$(ProjectDir)..\out\Iris.Iml\Iris.Iml.dll')" />
			<!-- Native hot-path library (optional; built by scripts/build-native.sh) -->
			<FilesToCopy Include="$(ProjectDir)..\out\native\iridium_core.dll" Condition="'$(OS)' == 'Windows_NT' And Exists('$(ProjectDir)..\out\native\iridium_core.dll')" />
			<FilesToCopy Include="$(ProjectDir)..\out\native\libiridium_core.so" Condition="Exists('$(ProjectDir)..\out\native\libiridium_core.so')" />
			<FilesToCopy Include="$(ProjectDir)..\out\native\libiridium_core.dylib" Condition="Exists('$(ProjectDir)..\out\native\libiridium_core.dylib')" />
			<FilesToCopy Include="$(ProjectDir)Info.json" />
			<ResourceFiles Include="$(ProjectDir)Resources\**\*" Exclude="$(ProjectDir)Resources\**\*\" />
		</ItemGroup>
		<Copy SourceFiles="@(FilesToCopy)" DestinationFolder="$(OutDir)" SkipUnchangedFiles="true" ContinueOnError="true" />
		<Copy SourceFiles="@(ResourceFiles)" DestinationFolder="$(OutDir)Resources\%(RecursiveDir)" SkipUnchangedFiles="true" />
		<Message Text="Files copied to: $(OutDir)" Importance="high" />
	</Target>
	<PropertyGroup>
		<AutoLaunchGame>true</AutoLaunchGame>
		<Loader></Loader>
	</PropertyGroup>
	<!-- Game exe path resolved from v3/.env (see ..\GamePath.props): the key
	     matching -p:Loader= wins, then the shared ADOFAI_GAME_PATH default.
	     A -p:GameExePath=... global property overrides all of this.
	     When no path resolves, DeployAndLaunch is skipped (build still succeeds). -->
	<Import Project="$(MSBuildThisFileDirectory)..\GamePath.props" />
	<PropertyGroup>
		<GameExePath Condition="'$(Loader)' == 'UMM'">$(GameExePath_UMMFinal)</GameExePath>
		<GameExePath Condition="'$(Loader)' == 'ML'">$(GameExePath_MLFinal)</GameExePath>
		<GameExePath Condition="'$(Loader)' == 'BepInEx'">$(GameExePath_BEPINEXFinal)</GameExePath>
		<GameExePath Condition="'$(GameExePath)' == ''">$(GameExePath_DefaultFinal)</GameExePath>
	</PropertyGroup>
	<Target Name="SkipDeployNotice" AfterTargets="DeployAndLaunch" Condition="'$(Loader)' != '' AND ('$(GameExePath)' == '' OR !Exists('$(GameExePath)'))">
		<Message Text="GameExePath is not set or not found — deploy skipped. Set ADOFAI_GAME_PATH in v3/.env (see v3/.env.example) to enable deploy+launch." Importance="high" />
	</Target>
	<Target Name="ValidateLoader" BeforeTargets="DeployAndLaunch" Condition="'$(Loader)' != '' AND '$(Loader)' != 'ML' AND '$(Loader)' != 'UMM' AND '$(Loader)' != 'BepInEx'">
		<Error Text="Invalid Loader value '$(Loader)'. Use -p:Loader=ML, -p:Loader=UMM, or -p:Loader=BepInEx" />
	</Target>
	<Target Name="DeployAndLaunch" AfterTargets="CopyToOut" Condition="'$(Loader)' != '' AND '$(GameExePath)' != '' AND Exists('$(GameExePath)')">
		<PropertyGroup>
			<GameDir>$([System.IO.Path]::GetDirectoryName($(GameExePath)))</GameDir>
			<ModsDir Condition="'$(Loader)' == 'UMM'">$(GameDir)\Mods\$(AssemblyName)\</ModsDir>
			<ModsDir Condition="'$(Loader)' == 'ML'">$(GameDir)\Mods\</ModsDir>
			<ModsDir Condition="'$(Loader)' == 'BepInEx'">$(GameDir)\BepInEx\plugins\$(AssemblyName)\</ModsDir>
		</PropertyGroup>
		<MakeDir Directories="$(ModsDir)" />
		<MakeDir Directories="$(ModsDir)Resources" />
		<ItemGroup>
			<ModFiles Include="$(ProjectDir)..\out\v3\*.*" Exclude="$(ProjectDir)..\out\v3\Resources\**\*" />
			<ModResourceFiles Include="$(ProjectDir)..\out\v3\Resources\**\*" Exclude="$(ProjectDir)..\out\v3\Resources\**\*\" />
		</ItemGroup>
		<Copy SourceFiles="@(ModFiles)" DestinationFolder="$(ModsDir)" SkipUnchangedFiles="true" />
		<Copy SourceFiles="@(ModResourceFiles)" DestinationFolder="$(ModsDir)Resources\%(RecursiveDir)" SkipUnchangedFiles="true" />
		<Message Text="Mod deployed to: $(ModsDir)" Importance="high" />
		<Exec Command="&quot;$(GameExePath)&quot; &amp;" WorkingDirectory="$(GameDir)" IgnoreExitCode="true" Condition="'$(AutoLaunchGame)' == 'true' And $([MSBuild]::IsOSPlatform('Linux'))" />
		<Exec Command="start &quot;&quot; &quot;$(GameExePath)&quot;" IgnoreExitCode="true" Condition="'$(AutoLaunchGame)' == 'true' And $([MSBuild]::IsOSPlatform('Windows'))" />
		<Message Text="Game launched: $(GameExePath)" Importance="high" Condition="'$(AutoLaunchGame)' == 'true'" />
		<Message Text="Auto-launch disabled. Game not started." Importance="high" Condition="'$(AutoLaunchGame)' != 'true'" />
	</Target>
</Project>
